name: Remove pre-merge tests!
on:
  pull_request:
    paths:
      - 'tests/pre-merge/*.ipynb'
    pull_request_target:
      branches:
        - master
jobs:
  Block-Merge:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Merge tests present
        run: |
          echo " ⚠️  Please remove ipynb files from tests/pre-merge before merging into the main branch! ⚠️ "
          exit 1
